### ISSUE TITLE
Guide me

### ISSUE THREAD

**Issue by SanjaySargam** [Bonfida/sns-manager#12] opened 2023-06-17 13:40 UTC
I cloned the repo
What are the commands which I need to run and which is the best editor - VS studio or Android Studio?
Will you please guide me step by step

**Comment by dr497** [comment] 2023-06-18 03:22
Hi @SanjaySargam!

To get started you will need a computer with Node and NPM (or Yarn) installed. You can use Volta to install Node https://volta.sh. If you want to use Yarn as your dependency manager instead of NPM you will need to run `volta install yarn`.

Once you are set up:

- Clone the repository on your computer `git clone https://github.com/Bonfida/sns-manager.git`
- Go into the SNS Manager directory `cd sns-manager`
- Install the dependencies `npm i` (or `yarn`)
- To run the app in dev mode:
    - xNFT dev mode: `npm run dev:xnft` or `yarn dev:xnt`
    - Web dev mode: `npm run dev:web` or `yarn dev:web`

**Comment by SanjaySargam** [comment] 2023-06-19 04:11
Thanks a lot @dr497

**Comment by SanjaySargam** [comment] 2023-06-19 07:15
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
Unexpected token '||='
[1] Starting project at C:\Users\SanjaySargam\Downloads\Bonfida\sns-manager
[1] › Port 19000 is
[1] Input is required, but 'npx expo' is in non-interactive mode.
[1] Required input:
[1] > Use port 19001 instead?
[1] › Skipping dev server
Job [1], 'GENERATE_SOURCEMAP=false expo start --clear --web' has ended

Sometimes I am getting this error while running `yarn dev:web` command
What's the reason?

**Comment by dr497** [comment] 2023-06-21 09:34
The error message you posted is a bit complex and I am not able to reproduce on my end.

- `Unexpected token '||='`: What Javascript engine are you using? 
- `Use port 19001 instead` Suggests that you already have a process running on this port, I would suggest closing it before starting the app

**Comment by SanjaySargam** [comment] 2023-06-21 09:47
I am not getting this error anymore
Btw Thanks♥️♥️

**Closed** 2023-06-21 10:39 UTC
